#!/bin/zsh

if [ "$#" -eq 2 ]; then
  echo "Left screen: $1, right screen: $2"
  swaymsg "output $1 enable"
  swaymsg "output $2 enable"
  swaymsg "output $1 pos 0 0"
  swaymsg "output $2 pos 1920 0"
  exit 0
fi

if [ "$#" -eq 1 ]; then
  if [ "$1" = "show" ]; then
    outputs=$(swaymsg -t get_outputs)
    name=$(echo $outputs | jq -r '.[].name')
    id=$(echo $outputs | jq -r '.[].id')
    enabled=$(echo $outputs | jq -r '.[].active')
    x=$(echo $outputs | jq -r '.[].rect.x')
    w=$(echo $outputs | jq -r '.[].rect.width')
    name=(${(f)name})
    id=(${(f)id})
    enabled=(${enabled:gs/true/enabled})
    enabled=(${(f)enabled:gs/false/disabled})
    x=(${(f)x})
    w=(${(f)w})
    for ((i = 1; i <= ${#name}; i++))
    do
      printf -- "Output %-2d %-9s %-9s x: %4d  res: %4d\n" "${id[$i]}" "${name[$i]}" "${enabled[$i]}" "$x[$i]" "$w[$i]"

    done
    exit 0
  fi
  echo "Using predefined config $1"
  if  [ "$1" = "office" ]; then
    swaymsg "output eDP-1 disable"
    swaymsg "output DP-3 enable pos 0 0"
    swaymsg "output DP-4 enable pos 1920 0"
    exit 0
  elif [ "$1" = "home" ]; then
    swaymsg "output eDP-1 disable"
    swaymsg "output DP-3 resolution 2560x1440 enable position 0 0"
    swaymsg "output HDMI-A-2 pos 2560 0 enable"
    exit 0
  elif [ "$1" = "home-alt" ]; then
    swaymsg "output HDMI-A-2 enable pos 0 0"
    swaymsg "output eDP-1 enable pos 1920 0"
    exit 0
  elif [ "$1" = "x1" ]; then
    swaymsg "output eDP-1 disable"
    swaymsg "output DP-1 resolution 2560x1440 enable pos 2560 0"
    swaymsg "output HDMI-A-1 enable pos 0 0"
    exit 0
  elif [ "$1" = "x1-alt" ]; then
    swaymsg "output eDP-1 disable"
    swaymsg "output DP-3 resolution 2560x1440 enable position 0 0"
    swaymsg "output HDMI-A-1 pos 2560 0 enable"
    exit 0
  elif [ "$1" = "alone" ]; then
    swaymsg "output * disable"
    swaymsg "output eDP-1 enable"
    exit 0
  elif  [ "$1" = "office-alt" ]; then
    swaymsg "output eDP-1 disable"
    swaymsg "output DP-5 enable pos 0 0"
    swaymsg "output DP-6 enable pos 1920 0"
    exit 0
  elif  [ "$1" = "tv" ]; then
    swaymsg "output eDP-1 enable pos 0 0"
    swaymsg "output HDMI-A-2 enable resolution 2560x1440 pos 1920 0"
    exit 0
  fi
fi

echo "Unknown args '$1 $2'\n"
echo "Usage:"
echo "office      DP-3     DP-4"
echo "home        DP-1     HDMI-A-2"
echo "alone       eDP1"
echo "x1          DP-1     HDMI-A-1"
echo "tv          eDP-1    HDMI-A-2"
echo "office-alt  DP-5     DP6"
echo "home-alt    eDP-1    HDMI-A-2"
echo "x1-alt      DP-3     HDMI-A-1"
echo " "
echo "<left> <right>"
echo " "
echo "show        Print connected monitors"
exit 1

# TODO: automatically determine inputs from swaymsg -t output -raw

