command_timeout = 1000

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[time]
disabled = false

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"

[[battery.display]]
threshold = 25
style = "bold red"

[memory_usage]
disabled = false
threshold = 80

[directory]
truncation_length = 5
#suffix = "▶"
#style = "white bold bg:#00819e"
style = "bold #00819e"
fish_style_pwd_dir_length = 1
# before_repo_root_style = "bold #AA1111"
repo_root_style = "bold #62c1be"

#[git_branch]
#style = "bg:purple bold"
#suffix = "▶"

#[git_status]
#style = "bg:purple bold "
#suffix = "\ue0b0"

[git_commit]
tag_disabled = false

[container]
disabled = true

[env_var.DEVWRAP]
default = ''
style = "bold red"
format = "in $env_value(bold red) "

