
# Fallback icon
default_icon = "•"

# Format string for determining the new workspace name. Placeholders are
# %n  number of the workspace
# %i  icon from the map below
format_str = "%n %i "

# Separator between workspace icons
icon_separator = " "

[icons]
"firefox" = ""
"google-chrome" = ""
"chromium" = ""
"alacritty" = ""
"kitty" = ""
"terminator" = ""
"chrome-faolna" = ""
"chrome-ompifgpmdd" = ""
"chrome-cifhbcnohmdccb" = ""
"ffpwa-01hv5y5dgy6aqy91t9yjqf6j3c" = ""
"ffpwa-01htptbg2fag8708nsx7rgrfnh" = ""
"emacs" = " "
"thunar" = " "
"org.kde.dolphin" = " "
"org.gnome.nautilus" = " "
"code" = " "
"spotify" = " "
"tm" = "󱩼"
"pm" = ""
"libreoffice" = "󱩼"
"evince" = ""
"okular" = ""
"zathura" = ""
"signal" = "󰍡"
"teams" = "󰍡"
"thunderbird" = "󰇮"
"evolution" = "󰇮"
"electron" = " "
"wine" = "🍷"
"shotwell" = ""
"imv" = ""
"zoom" = ""
"bitwarden" = ""
"desktopeditors" = ""
"nm-connection" = "🖧 "
"pavucontrol" = "🕪"
"draw.io" = ""
"keepass" = ""
"wfica" = ""
"remmina" = ""
"kicad" = ""
"org.wireshark" = "ﯳ"
"ffpwa-01jn36ppz49jp0pzrn3fe62y6j" = ""
"swappy" = " "
