
# Fallback icon
default_icon = "•"

# Format string for determining the new workspace name. Placeholders are
# %n  number of the workspace
# %i  icon from the map below
format_str = "%n %i "

# Separator between workspace icons
icon_separator = " "

[icons]
"firefox" = ""
"chrome" = ""
"chromium" = ""
"alacritty" = ""
"kitty" = ""
"terminator" = ""
"emacs" = " "
"thunar" = " "
"org.kde.dolphin" = " "
"org.gnome.nautilus" = " "
"code" = " "
"spotify" = " "
"tm" = "󱩼"
"pm" = ""
"libreoffice" = "󱩼"
"evince" = ""
"okular" = ""
"zathura" = ""
"signal" = "󰍡"
"teams" = "󰍡"
# "thunderbird" = "󰇮"
"thunderbird" = ""
"evolution" = "󰇮"
"electron" = " "
"wine" = "🍷"
"shotwell" = ""
"imv" = ""
"zoom" = ""
"bitwarden" = ""
"desktopeditors" = ""
"nm-connection" = "🖧 "
"pavucontrol" = "🕪"
"draw.io" = ""
"keepass" = ""
"chrome-faolna" = ""
"chrome-cifhbcno" = ""
"wfica" = ""
"remmina" = ""
